Feat/address copy
metrom-xyz/monorepo pull request #194
Opened 2024-09-18 14:39 UTC by divyam1705

- adds the ability to copy the account address

2024-09-18 16:57 UTC, luzzif requested changes

2024-09-18 16:57 UTC, luzzif commented on packages/frontend/src/components/connect-button/account-menu/index.tsx
> +        navigator.clipboard.writeText(account.address).then(() => {
From `caniuse` I see that this has roughly 93% of users support. I'm wondering if we should use a library to guarantee better compatibility or at least make this a bit more sophisticated.

2024-09-18 17:10 UTC, guerrap commented on packages/frontend/src/components/connect-button/account-menu/styles.module.css
> +    @apply flex items-center gap-3 hover:bg-gray-200 p-2 rounded-md cursor-pointer;
We should add the usual `duration-200 transition-colors ease-in-out` when we change styles on user interactions.

2024-09-19 09:40 UTC, 0xVenky commented
hey, looks good. I am wondering if we should extend the duration. It feels the copied state goes away immediately. Maybe keep it for 1.5 to 2 seconds?

2024-09-19 15:18 UTC, guerrap commented on packages/frontend/src/components/connect-button/account-menu/styles.module.css
> +        transition-[outline]
Let's have a transition for the background too.

2024-09-19 15:49 UTC, guerrap approved these changes

2024-09-19 16:03 UTC, luzzif approved these changes

2024-09-19 16:22 UTC, merged